config/routes.rb
Rails.application.routes.draw do

  resources :pokers do
    collection do
      get 'show_poker'
      post 'show_poker'
    end
  end

  get 'welcomes/index'

  resources :charts do
    collection do
      get 'basic_line'
    end
  end

  resources :test do
    collection do
      get 'get_poker'
    end
  end

  root 'welcomes#index'

end

app/controllers/pokers_controller.rb
class PokersController < ApplicationController
  def index
  end

  def show_poker

    hash_arr = {}
    time_arr = []
    tong_arr = []
    shun_arr = []
    search_time = params[:poker_time].present? ? params[:poker_time] : Time.current.strftime("%F")
    time = Time.parse(search_time)
    begin_mon = time.beginning_of_month
    end_mon = time.end_of_month

    while begin_mon < end_mon
      arr_al = PokerDate.where("poker_create_time > ? and poker_create_time < ? and state like ?", begin_mon.beginning_of_day, begin_mon.end_of_day, "%同花%").size
      tong_arr << arr_al

      arr_al = PokerDate.where("poker_create_time > ? and poker_create_time < ? and state like ?", begin_mon.beginning_of_day, begin_mon.end_of_day, "%顺子%").size
      shun_arr << arr_al

      time_arr << begin_mon.strftime("%F")
      begin_mon = begin_mon + 1.day
    end

    hash_arr["同花"] = tong_arr
    hash_arr["顺子"] = shun_arr
    @chart = ChartPoker.basic_line_chart(hash_arr,time_arr)
  end
end

app/helpers/pokers_helper.rb
module PokersHelper
end

app/views/pokers/index.html.erb
<h1>Pokers#index</h1>
<%= link_to 'poker_同花', show_poker_pokers_path %>


<div id="basic_line">
</div>

app/views/pokers/show_poker.html.erb
<%= form_tag  url: show_poker_pokers_path do  %>
  <span >操作时间：
    <%= text_field_tag  :poker_time, params[:poker_time], class: "pickerdate" %>
  </span>
  <%= button_tag "查询",class: "combtn_black btn_search" %>
  </p>
<% end %>


<div id="basic_line">
  <%= high_chart('chart_basic_line', @chart) %>
</div>

app/views/pokers/show_poker.js.erb
$('#basic_line')
.append("<%= escape_javascript(
  high_chart('chart_basic_line', @chart)) -%>")